---
mqti:
  workers: 4

mqtt:
  host: "mosquitto"
  port: "1883"
  client_id: "mqti"

influxdb:
  host: "influxdb"
  port: "8086"

mappings:
  - mqtt:
      topic: "temperature"
    influxdb:
      database: "iot"
      measurement: "temperature"
      tags:
        - something: "here"

  - mqtt:
      topic: "voltage"
      influxdb:
        database: "iot"
        measurement: "voltage"
