influxdb:
  image: influxdb:latest
  container_name: influxdb
  environment:
    INFLUXDB_ADMIN_ENABLED: "true"
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  environment:
    GF_INSTALL_PLUGINS: "grafana-worldmap-panel"
  ports:
    - "3000:3000"
  links:
    - influxdb

mosquitto:
  image: toke/mosquitto
  container_name: mosquitto
  ports:
    - "1883:1883"
    - "9001:9001"

mqti:
  image: ashmckenzie/mqti
  container_name: mqti
  volumes:
    - ./docker/config.yaml:/app/config.yaml:ro
  links:
    - influxdb
    - mosquitto

traffic_generator:
  image: toke/mosquitto
  container_name: traffic_generator
  command: "/bin/bash /app/traffic_generator.sh"
  volumes:
    - ./docker/traffic_generator.sh:/app/traffic_generator.sh:ro
  links:
    - mosquitto
